from __future__ import annotations

PROVIDER_NAME = "Microsoft-Windows-Kernel-Network"
PROVIDER_GUID = "{7DD42A49-5329-4832-8DFD-43D979153A88}"

KERNEL_NETWORK_KEYWORD_IPV4 = 0x10
KERNEL_NETWORK_KEYWORD_IPV6 = 0x20
KERNEL_NETWORK_KEYWORDS = KERNEL_NETWORK_KEYWORD_IPV4 | KERNEL_NETWORK_KEYWORD_IPV6

TRACE_LEVEL_INFORMATION = 4

EVENT_CONTROL_CODE_DISABLE_PROVIDER = 0
EVENT_CONTROL_CODE_ENABLE_PROVIDER = 1
EVENT_TRACE_CONTROL_STOP = 1

EVENT_TRACE_REAL_TIME_MODE = 0x00000100
# Prevent write failures in other sessions enabling this provider from suppressing our events.
EVENT_TRACE_INDEPENDENT_SESSION_MODE = 0x08000000
WNODE_FLAG_TRACED_GUID = 0x00020000

ERROR_SUCCESS = 0
ERROR_ACCESS_DENIED = 5
ERROR_INSUFFICIENT_BUFFER = 122
ERROR_ALREADY_EXISTS = 183
ERROR_CANCELLED = 1223
ERROR_CTX_CLOSE_PENDING = 7007
ERROR_WMI_INSTANCE_NOT_FOUND = 4201

# Manifest-backed event identities for Microsoft-Windows-Kernel-Network.
# TCP task 10 uses opcodes 10/11 for send/receive.
# UDP task 11 uses opcodes 42/43 for send/receive.
TCP_TASK = 10
TCP_SEND_OPCODE = 10
TCP_RECEIVE_OPCODE = 11
UDP_TASK = 11
UDP_SEND_OPCODE = 42
UDP_RECEIVE_OPCODE = 43
SUPPORTED_EVENT_VERSION = 0
